language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt
script: py.test

#
# Then repo is configured on Travis CI to build pull requests and Branches
# As for branches though, we only want Master to build (after a merge of a PR)
#
branches:
  only:
    - master

# run the packaging script after tests but before deploy
after_success:
  - ./scripts/digest.sh
  - ./scripts/package-artifact.sh
# test aws cli
  - pip install awscli
  - AWS_ACCESS_KEY_ID=$ARTIFACTS_KEY AWS_SECRET_ACCESS_KEY=$ARTIFACTS_SECRET aws s3 ls

# define the S3 deploy (https://docs.travis-ci.com/user/deployment/s3)
deploy:
  # Set skip_cleanup to true to prevent Travis CI from deleting your build artifacts
  skip_cleanup: true
  provider: s3
  # define the $ values as Environment Variables
  # https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings
  access_key_id: $ARTIFACTS_KEY
  secret_access_key: $ARTIFACTS_SECRET
  bucket: $ARTIFACTS_BUCKET
  # the AWS region our bucket resides in
  region: us-west-2
  # only upload the build dir
  local_dir: build
